swagger: "2.0"
info:
  description: "Ultra-simple bank account application. Supports create account, view account &amp; transfer balance methods"
  version: "1.0.0"
  title: "Thin Accounting"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "cikasfm@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
tags:
  - name: "account"
    description: "Everything about your Accounts"
schemes:
  - "https"
  - "http"
paths:
  /account:
    put:
      tags:
        - "account"
      summary: "Create a new Account"
      description: "Saves a new Account object in DB, generates account number"
      operationId: "create"
      parameters:
        - name: "accountName"
          type: "string"
          in: "query"
          description: "Account Name"
          required: true
      responses:
        200:
          description: "Account Created"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                format: "int32"
              message:
                type: "string"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Account"
        400:
          description: "Account Name null or empty"
  /account/all:
    get:
      tags:
        - "account"
      summary: "Find all accounts in the datastore"
      description: "Returns all account"
      operationId: "findAll"
      produces:
        - "application/json"
      parameters:
        - name: "pageNum"
          in: "query"
          description: "Page Number. Default is 0"
          required: false
          type: "integer"
          format: "int64"
          default: 0
        - name: "pageSize"
          in: "query"
          description: "Page Size. Default is 20"
          required: false
          type: "integer"
          format: "int64"
          default: 20
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                format: "int32"
              message:
                type: "string"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Account"
        400:
          description: "Invalid accountNumber supplied"
        404:
          description: "Account not found"
  /account/{accountNumber}:
    get:
      tags:
        - "account"
      summary: "Find Account by accountNumber"
      description: "Returns a single account"
      operationId: "findByAccountNumber"
      produces:
        - "application/json"
      parameters:
        - name: "accountNumber"
          in: "path"
          description: "accountNumber of account to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status:
                type: "integer"
                format: "int32"
              message:
                type: "string"
              data:
                $ref: "#/definitions/Account"
        400:
          description: "Invalid accountNumber supplied"
        404:
          description: "Account not found"
  /balance/transfer:
    post:
      tags:
        - "balance"
      summary: "Transfer Balance"
      description: "Transfers a specified balance from one account to another"
      operationId: "transferBalance"
      parameters:
        - in: "body"
          name: "TransferDTO"
          schema:
            $ref: "#/definitions/TransferDTO"
      responses:
        200:
          description: "Account Created"
        400:
          description: "Account Name null or empty"
definitions:
  Account:
    type: "object"
    properties:
      accountNumber:
        type: "integer"
        format: "int64"
        description: "Account Number"
      accountName:
        type: "integer"
        description: "Account Name"
      balance:
        type: "number"
        description: "Account Balance in local currency"
  TransferDTO:
    type: "object"
    properties:
      fromAcct:
        type: "integer"
        format: "int64"
        description: "Account Number to transfer FROM"
      toAcct:
        type: "integer"
        format: "int64"
        description: "Account Number to transfer TO"
      amount:
        type: "number"
        description: "Transfer amount in local currency"