swagger: "2.0"
info:
  description: "Ultra-simple bank account application. Supports create account, view account &amp; transfer balance methods"
  version: "1.0.0"
  title: "Thin Bank"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "cikasfm@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
tags:
  - name: "account"
    description: "Everything about your Accounts"
schemes:
  - "https"
  - "http"
paths:
  /account:
    put:
      tags:
        - "account"
      summary: "Create a new Account"
      description: "Saves a new Account object in DB, generates account number"
      operationId: "create"
      parameters:
        - name: "accountName"
          type: "string"
          in: "query"
          description: "Account Name"
          required: true
      responses:
        200:
          description: "Account Created"
          schema:
            type: "object"
            allOf:
              - $ref: "#/definitions/StandardResponse"
              - properties:
                  data:
                    $ref: "#/definitions/Account"
        400:
          description: "Account Name null or empty"
          schema:
            $ref: "#/definitions/StandardResponse"
  /account/all:
    get:
      tags:
        - "account"
      summary: "Find all accounts in the datastore"
      description: "Returns all account"
      operationId: "findAll"
      produces:
        - "application/json"
      parameters:
        - name: "pageNum"
          in: "query"
          description: "Page Number. Default is 0"
          required: false
          type: "integer"
          format: "int64"
          default: 0
        - name: "pageSize"
          in: "query"
          description: "Page Size. Default is 20"
          required: false
          type: "integer"
          format: "int64"
          default: 20
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            allOf:
              - $ref: "#/definitions/StandardResponse"
              - properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/definitions/Account"
  /account/{accountNumber}:
    get:
      tags:
        - "account"
      summary: "Find Account by accountNumber"
      description: "Returns a single account"
      operationId: "findByAccountNumber"
      produces:
        - "application/json"
      parameters:
        - name: "accountNumber"
          in: "path"
          description: "accountNumber of account to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            allOf:
              - $ref: "#/definitions/StandardResponse"
              - properties:
                  data:
                    $ref: "#/definitions/Account"
        400:
          description: "Invalid accountNumber supplied"
          schema:
            $ref: "#/definitions/StandardResponse"
        404:
          description: "Account not found"
          schema:
            $ref: "#/definitions/StandardResponse"
  /balance/transfer:
    post:
      tags:
        - "balance"
      summary: "Transfer Balance"
      description: "Transfers a specified balance from one account to another"
      operationId: "transferBalance"
      parameters:
        - in: "body"
          name: "TransferDTO"
          schema:
            $ref: "#/definitions/TransferDTO"
      responses:
        200:
          description: "Balance transferred"
          schema:
            $ref: "#/definitions/StandardResponse"
        400:
          description: |
            One of:
             - Account FROM or TO number is invalid or account does not exist
             - Amount is invalid - either negative, or has more than 2 decimal digits
             - Account balance is not sufficient
          schema:
            $ref: "#/definitions/StandardResponse"
  /balance/deposit:
    post:
      tags:
        - "balance"
      summary: "Deposit money"
      description: "Deposits a specified amount to an account"
      operationId: "deposit"
      parameters:
        - in: "body"
          name: "TransferDTO"
          schema:
            properties:
              toAcct:
                type: "integer"
                format: "int64"
                description: "Account Number to deposit TO"
              amount:
                type: "number"
                description: "Deposit amount in local currency"
      responses:
        200:
          description: "Deposit completed"
          schema:
            $ref: "#/definitions/StandardResponse"
        400:
          description: |
            One of:
             - Account TO number is invalid or account does not exist
             - Amount is invalid - either negative, or has more than 2 decimal digits
          schema:
            $ref: "#/definitions/StandardResponse"
  /balance/withdraw:
    post:
      tags:
        - "balance"
      summary: "Withdraw money"
      description: "Withdraws a specified amount from an account"
      operationId: "withdraw"
      parameters:
        - in: "body"
          name: "TransferDTO"
          schema:
            properties:
              fromAcct:
                type: "integer"
                format: "int64"
                description: "Account Number to withdraw FROM"
              amount:
                type: "number"
                description: "Withdrawal amount in local currency"
      responses:
        200:
          description: "Withdrawal completed"
          schema:
            $ref: "#/definitions/StandardResponse"
        400:
          description: |
            One of:
             - Account TO number is invalid or account does not exist
             - Amount is invalid - either negative, or has more than 2 decimal digits
             - Account balance is not sufficient
          schema:
            $ref: "#/definitions/StandardResponse"
definitions:
  StandardResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  Account:
    type: "object"
    properties:
      accountNumber:
        type: "integer"
        format: "int64"
        description: "Account Number"
      accountName:
        type: "integer"
        description: "Account Name"
      balance:
        type: "number"
        description: "Account Balance in local currency"
  TransferDTO:
    type: "object"
    properties:
      fromAcct:
        type: "integer"
        format: "int64"
        description: "Account Number to transfer FROM"
      toAcct:
        type: "integer"
        format: "int64"
        description: "Account Number to transfer TO"
      amount:
        type: "number"
        description: "Transfer amount in local currency"